import React,{useEffect,useRef,useState} from 'react';
export type Placement={page:number;x:number;y:number;width:number};
export async function pdfPreview(path:string,body:unknown,csrf:string){
 const response=await fetch('/api/v1'+path,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(body),signal:AbortSignal.timeout(60000)});
 if(!response.ok){const data=await response.json();if(response.status===401)window.dispatchEvent(new Event('erp-session-expired'));throw new Error(data.message||'Không tạo được PDF xem trước.');}return URL.createObjectURL(await response.blob());
}
export function SigningControls({value,onChange,disabled=false,maxPage=12}:{value:Placement;onChange:(p:Placement)=>void;disabled?:boolean;maxPage?:number}){
 return <div className="list-toolbar"><label>Trang ký<input type="number" min="1" max={maxPage} disabled={disabled} value={value.page} onChange={e=>onChange({...value,page:Number(e.target.value)})}/></label>{(['x','y','width'] as const).map((k,i)=><label key={k}>{['Ngang (%)','Dọc (%)','Chiều rộng ảnh (%)'][i]}<input type="number" disabled={disabled} min={k==='width'?4:0} max={k==='width'?60:100} value={Math.round(value[k]*100)} onChange={e=>onChange({...value,[k]:Number(e.target.value)/100})}/></label>)}</div>;
}
type Props={id:string;updatedAt:string;csrf:string;permissions:string[];request:(path:string,body?:unknown,csrf?:string)=>Promise<any>;onChange:()=>Promise<void>};
export function FinancialReview(props:Props){
 const [data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[changes,setChanges]=useState<Record<number,string>>({}),[reason,setReason]=useState(''),[placement,setPlacement]=useState<Placement>({page:1,x:.55,y:.7,width:.28}),[confirmed,setConfirmed]=useState(false),[preview,setPreview]=useState(''),[previewError,setPreviewError]=useState(false);
 const canvas=useRef<HTMLDivElement>(null),drag=useRef<{dx:number;dy:number}|null>(null),base='/output-recon/uploads/'+props.id;
 async function load(){const v=await props.request(base+'/financial');setData(v);setChanges({});setConfirmed(false);return v;}
 useEffect(()=>{let done=false;void props.request(base+'/financial').then(v=>{if(!done){setData(v);setChanges({});setConfirmed(false);}}).catch(e=>{if(!done)setMessage(e.message);});return()=>{done=true;};},[props.id,props.updatedAt]);
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview);},[preview]);
 function changed(p:Placement){setPlacement(p);setConfirmed(false);setPreview('');}
 async function correct(){setBusy(true);setMessage('');try{const v=await props.request(base+'/correct-financial',{expectedUpdatedAt:data.item.updatedAt,changes:Object.entries(changes).map(([lineNo,revenueMzn])=>({lineNo:Number(lineNo),revenueMzn})),reason},props.csrf);setData(v);setChanges({});setConfirmed(false);setPreview('');await props.onChange();setMessage('Đã lưu sửa Revenue MZN và tính lại WHT/Payable.');}catch(e){setMessage(e instanceof Error?e.message:'Không lưu được số liệu.');}finally{setBusy(false);}}
 const payload=()=>({expectedUpdatedAt:data.item.updatedAt,digest:data.digest,signingAssetId:data.signingAsset.id,placement,confirmed:true});
 async function signedPreview(){setBusy(true);setMessage('');try{setPreview(await pdfPreview(base+'/signed-preview',payload(),props.csrf));setConfirmed(false);}catch(e){setMessage(e instanceof Error?e.message:'Không xem được PDF.');}finally{setBusy(false);}}
 async function finalize(){setBusy(true);setMessage('');try{const v=await props.request(base+'/finalize',payload(),props.csrf);await load();await props.onChange();setMessage(v.message);setConfirmed(false);}catch(e){setMessage(e instanceof Error?e.message:'Không chốt được PDF.');}finally{setBusy(false);}}
 if(!data)return <p role="status">{message||'Đang tải kết quả tài chính…'}</p>;
 const f=data.financial,approved=data.item.status==='APPROVED',editable=['OCR_EXTRACTED','UNDER_REVIEW'].includes(data.item.status),dirty=Object.keys(changes).length>0;
 const names:Record<string,string>={totalServiceRevenue:'Tổng doanh thu dịch vụ',ivaTax:'IVA',serviceRevenueForSharing:'Doanh thu chia sẻ',remunerationProvider:'Revenue',wht:'WHT',partnerRevenue:'Payable'};
 const amount=(v:string|undefined)=>v===undefined?'—':new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v));
 return <section className="financial-review"><h3>Kết quả đối soát doanh thu</h3>{message&&<p className="notice" role="alert">{message}</p>}<p><b>Tỷ giá MZN / USD:</b> {f.exchangeRate??'Chưa đọc được'}</p>
 <div className="table-scroll"><table><thead><tr><th>Chỉ tiêu</th><th>MZN</th><th>USD</th></tr></thead><tbody>{Object.entries(names).map(([key,label])=><tr key={key}><td>{label}</td><td className="number">{amount(f.mzn?.[key])}</td><td className="number">{amount(f.usd?.[key])}</td></tr>)}</tbody></table></div>
 <div className="table-scroll"><table><thead><tr><th>Dịch vụ</th><th>Dòng</th><th>Revenue MZN</th><th>WHT MZN</th><th>Payable MZN</th><th>Revenue USD</th><th>WHT USD</th><th>Payable USD</th></tr></thead><tbody>{f.details.map((d:any)=><tr key={d.lineNo} className={d.rowType==='TOTAL'?'financial-total':''}><td>{d.serviceName}</td><td>{d.rowType==='TOTAL'?'Tổng tính Invoice':'Chi tiết'}</td><td>{editable&&f.ready&&props.permissions.includes('RECON_REVIEW')&&(d.rowType==='CHILD'||f.details.length===1)?<input aria-label={'Revenue MZN '+d.serviceName} type="text" inputMode="decimal" disabled={busy} value={changes[d.lineNo]??d.remunerationProvider} onChange={e=>{setChanges({...changes,[d.lineNo]:e.target.value});setConfirmed(false);setPreview('');}}/>:amount(d.remunerationProvider)}</td><td className="number">{amount(d.wht)}</td><td className="number">{amount(d.partnerRevenue)}</td><td className="number">{amount(d.usd.remunerationProvider)}</td><td className="number">{amount(d.usd.wht)}</td><td className="number">{amount(d.usd.partnerRevenue)}</td></tr>)}</tbody></table></div>
 <details><summary>Bảng chi tiết MZN và tỷ lệ chia sẻ</summary><div className="table-scroll"><table><thead><tr><th>Dịch vụ</th><th>Tổng doanh thu MZN</th><th>IVA MZN</th><th>Chi phí MZN</th><th>Doanh thu chia sẻ MZN</th><th>Tỷ lệ chia sẻ</th><th>Tỷ lệ phân phối</th></tr></thead><tbody>{f.details.map((d:any)=><tr key={d.lineNo}><td>{d.serviceName}</td><td>{amount(d.totalServiceRevenue)}</td><td>{amount(d.ivaTax)}</td><td>{amount(d.costDeduction)}</td><td>{amount(d.serviceRevenueForSharing)}</td><td>{d.ratesMissing?'Chưa đọc được':amount(String(Number(d.sharingRate)*100))+'%'}</td><td>{d.ratesMissing?'Chưa đọc được':amount(String(Number(d.distributionRatio)*100))+'%'}</td></tr>)}</tbody></table></div></details>
 {data.bindings.length>0&&<p className="hint">{data.bindings.map((b:any)=>b.serviceKey+' → '+b.contractCode).join(' · ')}</p>}{f.warnings.map((v:string,i:number)=><p key={i} className="notice">{v}</p>)}{!approved&&data.errors.map((v:string,i:number)=><p key={'e'+i} className="notice" role="alert">{v}</p>)}
 {editable&&props.permissions.includes('RECON_REVIEW')&&dirty&&<div className="list-toolbar"><label>Lý do sửa Revenue<input disabled={busy} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||!reason.trim()} onClick={()=>void correct()}>Lưu sửa và tính lại</button></div>}
 <h3>Preview scan và vị trí dấu/chữ ký/chức danh</h3><SigningControls value={placement} onChange={p=>{changed(p);setPreviewError(false);}} disabled={busy} maxPage={data.item.extractionData?.pages?.length??1}/>
 <div ref={canvas} className="signing-canvas">{previewError?<p className="notice">Không tải được preview. <button onClick={()=>setPreviewError(false)}>Tải lại</button></p>:<img className="scan-image" src={'/api/v1'+base+'/preview?page='+placement.page} alt={'PDF gốc, trang '+placement.page} onError={()=>setPreviewError(true)}/>}
 {data.signingAsset&&!previewError&&<img key={data.signingAsset.id} className="signing-overlay" src={'/api/v1/output-recon/signing-asset?v='+data.signingAsset.id} alt="Dấu, chữ ký và chức danh GST" draggable={false} style={{left:placement.x*100+'%',top:placement.y*100+'%',width:placement.width*100+'%'}} onPointerDown={e=>{if(busy)return;const rect=canvas.current!.getBoundingClientRect();drag.current={dx:e.clientX-rect.left-placement.x*rect.width,dy:e.clientY-rect.top-placement.y*rect.height};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(!drag.current)return;const rect=canvas.current!.getBoundingClientRect();changed({...placement,x:Math.max(0,Math.min(1-placement.width,(e.clientX-rect.left-drag.current.dx)/rect.width)),y:Math.max(0,Math.min(1-e.currentTarget.offsetHeight/rect.height,(e.clientY-rect.top-drag.current.dy)/rect.height))});}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}/>}</div>
 <p className="hint">Kéo ảnh tổng hợp đến vị trí cần ký. PDF gốc được giữ nguyên; bản chốt lưu riêng trong kho.</p>
 {props.permissions.includes('RECON_APPROVE')&&data.signingAsset&&(data.canFinalize||approved)&&<><button disabled={busy||dirty} onClick={()=>void signedPreview()}>Tạo PDF xem trước</button>{preview&&<p><a href={preview} target="_blank" rel="noreferrer">Mở PDF có dấu/chữ ký để kiểm tra</a></p>}<label className="check-label"><input type="checkbox" checked={confirmed} disabled={busy||dirty||!preview} onChange={e=>setConfirmed(e.target.checked)}/>{approved?'Tôi đã kiểm tra vị trí ảnh trên PDF mới.':'Tôi đã kiểm tra scan, số liệu và vị trí ảnh trên PDF xem trước.'}</label><button className="action-primary" disabled={busy||dirty||!confirmed} onClick={()=>void finalize()}>{busy?'Đang xử lý…':approved?'Lưu bản PDF mới':'Chốt PDF và doanh thu'}</button></>}
 {approved&&<p className="recon-match notice">Đã chốt đối soát và doanh thu. <a href={'/api/v1'+base+'/signed-download'}>Tải PDF đã chốt</a> · Chọn “Quản lý Invoice” để tạo Invoice.</p>}
 </section>;
}
