import React,{useEffect,useRef,useState} from 'react';
type Props={request:(path:string,body?:unknown,csrf?:string)=>Promise<any>;kind:'revenues'|'receivables';canDownload:boolean};
const labels:Record<string,string>={INVOICE_READY:'Đã chốt · Chờ Invoice',INVOICED:'Đã phát hành Invoice',PARTIALLY_PAID:'Thanh toán một phần',PAID:'Đã thanh toán',OPEN:'Chưa thanh toán',OVERDUE:'Quá hạn'};
const money=(v:string)=>new Intl.NumberFormat('vi-VN',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v));
const day=(v:string)=>v?.slice(0,10);
export function FinanceLedger({request,kind,canDownload}:Props){
 const [period,setPeriod]=useState(''),[details,setDetails]=useState(false),[asOf,setAsOf]=useState(new Date().toLocaleDateString('en-CA')),[page,setPage]=useState(1),[data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const loadSequence=useRef(0);
 async function load(){const sequence=++loadSequence.current;setBusy(true);setMessage('');try{const q=new URLSearchParams({page:String(page),...(period?{period}:{}),...(kind==='receivables'?{asOf}:{details:String(details)})});const result=await request('/'+kind+'?'+q);if(sequence===loadSequence.current)setData(result);}catch(e){if(sequence===loadSequence.current){setData(null);setMessage(e instanceof Error?e.message:'Không tải được danh sách.');}}finally{if(sequence===loadSequence.current)setBusy(false);}}
 useEffect(()=>{void load();return()=>{loadSequence.current++;};},[kind,period,details,asOf,page]);
 return <section className="panel"><div className="panel-heading"><div><h2>{kind==='revenues'?'Doanh thu từ đối soát đã chốt':'Phải thu từ Invoice đã phát hành'}</h2><p className="muted">{kind==='revenues'?'Tổng doanh thu chỉ tính dòng tổng; các dòng dịch vụ con dùng để kiểm tra chi tiết.':'Mỗi Invoice phát hành có một khoản phải thu USD. Invoice nháp chưa tạo công nợ.'}</p></div><button disabled={busy} onClick={()=>void load()}>Tải lại</button></div>
 <div className="partner-grid"><label>Kỳ doanh thu<input type="month" value={period} disabled={busy} onChange={e=>{setPeriod(e.target.value);setPage(1);}}/><span className="hint">Để trống để xem tất cả kỳ.</span></label>{kind==='receivables'?<label>Ngày tính quá hạn<input type="date" value={asOf} disabled={busy} onChange={e=>{setAsOf(e.target.value);setPage(1);}}/><span className="hint">Số dư hiện tại; ngày này chỉ dùng để tính số ngày quá hạn.</span></label>:<label className="check-label"><input type="checkbox" checked={details} disabled={busy} onChange={e=>{setDetails(e.target.checked);setPage(1);}}/>Hiện các dòng dịch vụ con</label>}</div>
 {message&&<p className="notice" role="alert">{message}</p>}{data&&<>{kind==='receivables'?<section className="cards"><article><b>Phải thu ban đầu USD</b><p>{money(data.totals.original)}</p></article><article><b>Đã thu USD</b><p>{money(data.totals.paid)}</p></article><article><b>Còn phải thu USD</b><p>{money(data.totals.outstanding)}</p></article></section>:null}
 <div className="table-scroll"><table><thead>{kind==='revenues'?<tr><th>Mã / nguồn đối soát</th><th>Đối tác / kỳ</th><th>Dịch vụ</th><th>Revenue USD</th><th>WHT USD</th><th>Payable USD</th><th>Trạng thái</th></tr>:<tr><th>Invoice / đối tác</th><th>Kỳ / ngày Invoice</th><th>Hạn thanh toán</th><th>Ban đầu USD</th><th>Đã thu USD</th><th>Còn phải thu USD</th><th>Trạng thái / quá hạn</th><th>Tài liệu</th></tr>}</thead><tbody>{data.items.map((i:any)=>kind==='revenues'?<tr key={i.id}><td>{i.revenueCode}<small>{i.reconciliation} · {i.contract}</small></td><td>{i.partner}<small>{i.period}</small></td><td>{i.service}{i.rowType==='CHILD'&&<small>Chi tiết · không cộng vào tổng</small>}</td><td className="number">{money(i.invoiceRevenueUsd)}</td><td className="number">{money(i.invoiceWhtUsd)}</td><td className="number">{money(i.invoicePayableUsd)}</td><td>{labels[i.status]??i.status}</td></tr>:<tr key={i.id}><td>{i.invoiceNumber}<small>{i.partner}</small></td><td>{i.period}<small>{day(i.invoiceDate)}</small></td><td>{day(i.dueDate)}</td><td className="number">{money(i.originalAmount)}</td><td className="number">{money(i.paidAmount)}</td><td className="number">{money(i.outstandingAmount)}</td><td>{labels[i.status]??i.status}<small>{i.agingDays>0?i.agingDays+' ngày quá hạn':'Trong hạn'}</small></td><td>{canDownload?<a href={'/api/v1/invoices/'+i.invoiceId+'/download'}>PDF Invoice</a>:'—'}</td></tr>)}</tbody></table></div>{!data.items.length&&<p className="muted">{kind==='revenues'?'Chưa có doanh thu đã chốt trong kỳ này.':'Chưa có khoản phải thu trong kỳ này.'}</p>}<div className="pagination"><span>{data.total} bản ghi · Trang {page}/{Math.max(1,Math.ceil(data.total/50))}</span><button disabled={busy||page===1} onClick={()=>setPage(page-1)}>Trang trước</button><button disabled={busy||page*50>=data.total} onClick={()=>setPage(page+1)}>Trang sau</button></div></>}
 </section>;
}
