import React,{useEffect,useRef,useState} from 'react';
import {pdfPreview,SigningControls,type Placement} from './FinancialReview';
type Props={permissions:string[];csrf:string;request:(path:string,body?:unknown,csrf?:string)=>Promise<any>};
const initialPlacement:Placement={page:1,x:.56,y:.82,width:.28};
function InvoiceCanvas({src,assetId,placement,onChange,disabled}:{src:string;assetId:string;placement:Placement;onChange:(p:Placement)=>void;disabled:boolean}){
 const area=useRef<HTMLDivElement>(null),drag=useRef<{x:number;y:number}|null>(null);
 return <div className="signing-canvas invoice-canvas" ref={area}><img className="scan-image" src={src} alt="Trang Invoice GST trước khi chèn ảnh"/><img className="signing-overlay" src={'/api/v1/invoices/signing-asset?v='+assetId} alt="Dấu, chữ ký, chức danh GST" draggable={false} style={{left:placement.x*100+'%',top:placement.y*100+'%',width:placement.width*100+'%'}} onPointerDown={e=>{if(disabled)return;const r=area.current!.getBoundingClientRect();drag.current={x:e.clientX-r.left-placement.x*r.width,y:e.clientY-r.top-placement.y*r.height};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(!drag.current)return;const r=area.current!.getBoundingClientRect();onChange({...placement,x:Math.max(0,Math.min(1-placement.width,(e.clientX-r.left-drag.current.x)/r.width)),y:Math.max(0,Math.min(1-e.currentTarget.offsetHeight/r.height,(e.clientY-r.top-drag.current.y)/r.height))});}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}/></div>;
}
export function Invoices(props:Props){
 const now=new Date(),[refs,setRefs]=useState<any[]>([]),[items,setItems]=useState<any[]>([]),[selection,setSelection]=useState({partnerId:'',period:new Date(Date.UTC(now.getFullYear(),now.getMonth()-1,1)).toISOString().slice(0,7),invoiceMode:'CONSOLIDATED',invoiceDate:now.toLocaleDateString('en-CA'),paymentTermDays:45}),[plan,setPlan]=useState<any>(null),[placements,setPlacements]=useState<Record<string,Placement>>({}),[pages,setPages]=useState<Record<string,string>>({}),[previews,setPreviews]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[confirmed,setConfirmed]=useState(false);
 const blobs=useRef<string[]>([]);
 useEffect(()=>()=>{for(const url of blobs.current)URL.revokeObjectURL(url);},[]);
 async function list(){const v=await props.request('/invoices');setItems(v.items);}
 useEffect(()=>{void Promise.all([props.request('/invoices/references'),props.request('/invoices')]).then(([r,l])=>{setRefs(r.partners);setItems(l.items);}).catch(e=>setMessage(e.message));},[]);
 function change(key:string,value:unknown){setSelection({...selection,[key]:value});setPlan(null);setConfirmed(false);setPages({});setPreviews({});}
 const payload=(key?:string)=>({...selection,digest:plan.digest,confirmed:true,placements:plan.invoices.filter((i:any)=>!key||i.businessKey===key).map((i:any)=>({businessKey:i.businessKey,placement:placements[i.businessKey]??initialPlacement}))});
 async function preview(){setBusy(true);setMessage('');try{const v=await props.request('/invoices/preview',selection,props.csrf);setPlan(v);setPlacements(Object.fromEntries(v.invoices.map((i:any)=>[i.businessKey,{...initialPlacement}])));setPages({});setPreviews({});setConfirmed(false);}catch(e){setMessage(e instanceof Error?e.message:'Không xem được Invoice.');}finally{setBusy(false);}}
 async function page(key:string,pdf=false){setBusy(true);setMessage('');try{const url=await pdfPreview(pdf?'/invoices/preview-pdf':'/invoices/preview-page',payload(key),props.csrf);blobs.current.push(url);if(pdf)setPreviews(v=>({...v,[key]:url}));else setPages(v=>({...v,[key]:url}));setConfirmed(false);}catch(e){setMessage(e instanceof Error?e.message:'Không tạo được bản xem trước.');}finally{setBusy(false);}}
 async function create(){setBusy(true);setMessage('');try{const v=await props.request('/invoices/create',payload(),props.csrf);setPlan(null);setConfirmed(false);setMessage(v.message);await list();}catch(e){setMessage(e instanceof Error?e.message:'Không tạo được Invoice.');}finally{setBusy(false);}}
 function position(key:string,p:Placement){const changedPage=p.page!==placements[key]?.page;setPlacements({...placements,[key]:p});setConfirmed(false);setPreviews(v=>({...v,[key]:''}));if(changedPage)setPages(v=>({...v,[key]:''}));}
 return <section className="panel"><h2>Invoice từ doanh thu đã chốt</h2><p className="muted">Tạo bản nháp PDF và workbook theo template GST, có dấu/chữ ký/chức danh.</p>{message&&<p className="notice" role="alert">{message}</p>}
 {props.permissions.includes('INVOICE_CREATE')&&<><div className="partner-grid"><label>Đối tác<select disabled={busy} value={selection.partnerId} onChange={e=>change('partnerId',e.target.value)}><option value="">Chọn đối tác</option>{refs.map(p=><option key={p.id} value={p.id}>{p.partnerKey} · {p.legalName}</option>)}</select></label><label>Kỳ doanh thu<input disabled={busy} type="month" value={selection.period} onChange={e=>change('period',e.target.value)}/></label><label>Chế độ Invoice<select disabled={busy} value={selection.invoiceMode} onChange={e=>change('invoiceMode',e.target.value)}><option value="CONSOLIDATED">Gộp tất cả dịch vụ</option><option value="PER_SERVICE">Tách theo dịch vụ</option></select></label><label>Ngày Invoice<input disabled={busy} type="date" value={selection.invoiceDate} onChange={e=>change('invoiceDate',e.target.value)}/></label><label>Hạn thanh toán (ngày)<input disabled={busy} type="number" min="0" max="365" value={selection.paymentTermDays} onChange={e=>change('paymentTermDays',Number(e.target.value))}/></label></div><button className="action-primary" disabled={busy||!selection.partnerId} onClick={()=>void preview()}>Xem trước Invoice</button></>}
 {plan&&<section className="invoice-preview">{plan.warnings.map((w:string,i:number)=><p className="notice" key={i}>{w}</p>)}{plan.invoices.map((i:any)=><article key={i.businessKey}><h3>{i.invoice.invoiceNumber} · {i.previousDraft?'Bản thay thế Nháp v'+(i.previousDraft.revisionNo+1):'Nháp mới'}</h3><p>{i.invoice.partner.name} · {i.invoice.period} · Hạn: {i.invoice.dueDate}</p><div className="table-scroll"><table><thead><tr><th>Dịch vụ</th><th>Revenue USD</th><th>WHT USD</th><th>Payable USD</th></tr></thead><tbody>{i.invoice.lines.map((l:any,j:number)=><tr key={j}><td>{l.serviceName}</td><td className="number">{l.revenue}</td><td className="number">{l.wht}</td><td className="number">{l.payable}</td></tr>)}<tr className="financial-total"><td>Tổng</td><td className="number">{i.invoice.totals.revenue}</td><td className="number">{i.invoice.totals.wht}</td><td className="number">{i.invoice.totals.payable}</td></tr></tbody></table></div><p>{i.invoice.amountInWords}</p><SigningControls value={placements[i.businessKey]} disabled={busy} onChange={p=>position(i.businessKey,p)}/><button disabled={busy} onClick={()=>void page(i.businessKey)}>Tải trang để kéo dấu/chữ ký</button>{pages[i.businessKey]&&<InvoiceCanvas src={pages[i.businessKey]} assetId={plan.signingAsset.id} placement={placements[i.businessKey]} disabled={busy} onChange={p=>position(i.businessKey,p)}/>}<button disabled={busy} onClick={()=>void page(i.businessKey,true)}>Tạo PDF có dấu để kiểm tra</button>{previews[i.businessKey]&&<p><a href={previews[i.businessKey]} target="_blank" rel="noreferrer">Mở PDF Invoice xem trước</a></p>}</article>)}<label className="check-label"><input type="checkbox" checked={confirmed} disabled={busy||plan.invoices.some((i:any)=>!previews[i.businessKey])} onChange={e=>setConfirmed(e.target.checked)}/>Tôi đã kiểm tra số liệu, thông tin Invoice và vị trí ảnh trên từng PDF.</label><button className="action-primary" disabled={busy||!confirmed} onClick={()=>void create()}>{busy?'Đang xử lý…':'Chốt và lưu Invoice nháp'}</button></section>}
 <h3>Invoice đã lưu</h3><button disabled={busy} onClick={()=>void list().catch(e=>setMessage(e.message))}>Tải lại danh sách</button><div className="table-scroll"><table><thead><tr><th>Số Invoice</th><th>Đối tác / kỳ</th><th>Trạng thái</th><th>Payable USD</th><th>Tài liệu</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td>{i.invoiceNumber}<small>Phiên bản {i.revisionNo}</small></td><td>{i.partner.legalName}<small>{i.period}</small></td><td>{i.status==='DRAFT'?'Nháp':i.status==='SUPERSEDED'?'Đã thay thế':i.status}</td><td className="number">{i.payableAmount}</td><td><a href={'/api/v1/invoices/'+i.id+'/download'}>PDF</a> · <a href={'/api/v1/invoices/'+i.id+'/download?format=workbook'}>Excel</a></td></tr>)}</tbody></table></div>{!items.length&&<p className="muted">Chưa có Invoice.</p>}</section>;
}
