import React,{useEffect,useState} from 'react';
type Props={request:(path:string,body?:unknown,csrf?:string)=>Promise<any>;csrf:string;permissions:string[];onSaved:()=>void};
const row=()=>({period:new Date().toISOString().slice(0,7),serviceId:'',contractId:'',currency:'VND',amount:'',deduction:'0',fxRate:'',note:''});
const num=(v:any,c='USD')=>v===null||v===undefined?'Chưa có tỷ giá':new Intl.NumberFormat('vi-VN',{minimumFractionDigits:c==='VND'?0:2,maximumFractionDigits:c==='VND'?0:2}).format(Number(v));
const fileData=async(file:File)=>{if(file.size>5*1024*1024)throw new Error('Tệp tối đa 5 MB.');return {filename:file.name,base64:await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file);})};};
export function ManualRevenue({request,csrf,permissions,onSaved}:Props){
 const [refs,setRefs]=useState<any>({partners:[],services:[],contracts:[]}),[partner,setPartner]=useState(''),[rows,setRows]=useState([row()]),[source,setSource]=useState<File|null>(null),[items,setItems]=useState<any[]>([]),[page,setPage]=useState(1),[total,setTotal]=useState(0),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[opened,setOpened]=useState(false),[rates,setRates]=useState<any[]>([]),[fx,setFx]=useState({period:new Date().toISOString().slice(0,7),rate:'',source:''});
 const canCreate=permissions.includes('RECON_UPLOAD');
 async function list(){const v=await request('/manual-revenue/drafts?page='+page);setItems(v.items);setTotal(v.total);}
 useEffect(()=>{void Promise.all([request('/manual-revenue/references'),request('/revenue-fx')]).then(([r,f])=>{setRefs(r);setRates(f.items);}).catch(e=>setMessage(e.message));},[]);
 useEffect(()=>{void list().catch(e=>setMessage(e.message));},[page]);
 function change(i:number,key:string,value:string){setRows(v=>v.map((r,j)=>j===i?{...r,[key]:value,...(key==='serviceId'?{contractId:''}:{})}:r));}
 function template(){const csv='period,serviceCode,contractCode,currency,amount,deduction,fxRate,note\r\n'+new Date().toISOString().slice(0,7)+',FILM_CINETOP,MA_HOP_DONG,VND,25000000,0,25000,So GST duoc huong\r\n',url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='Revenue_Import_Template.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function importFile(file:File){setBusy(true);setMessage('');try{const r=await request('/manual-revenue/import-preview',{partnerId:partner,file:await fileData(file)},csrf);setRows(r.rows.map((v:any)=>Object.fromEntries(Object.keys(row()).map(k=>[k,v[k]]))));setSource(file);setMessage(r.message);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function save(){setBusy(true);setMessage('');try{const r=await request('/manual-revenue/drafts',{partnerId:partner,rows,source:source?await fileData(source):undefined},csrf);setMessage(r.message);setRows([row()]);setSource(null);setOpened(false);await list();onSaved();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function act(i:any,action:string){if(!window.confirm(action==='approve'?'Duyệt số liệu GST được hưởng của '+i.reconCode+' và ghi nhận doanh thu '+num(i.payload.amount,i.payload.currency)+' '+i.payload.currency+'?':action==='cancel'?'Hủy bản chưa duyệt '+i.reconCode+'?':'Gửi bản '+i.reconCode+' để kiểm tra và duyệt?'))return;setBusy(true);setMessage('');try{const r=await request('/manual-revenue/'+i.id+'/'+action,{expectedUpdatedAt:i.updatedAt,confirmed:true},csrf);setMessage(r.message);await list();onSaved();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function saveFx(){if(!window.confirm('Lưu tỷ giá báo cáo kỳ '+fx.period+'? Tỷ giá đã lưu không sửa; không thay đổi số tiền Invoice/công nợ.'))return;setBusy(true);setMessage('');try{const r=await request('/revenue-fx',{...fx,confirmed:true},csrf);setMessage(r.message);setRates((await request('/revenue-fx')).items);onSaved();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel"><div className="panel-heading"><div><h2>Doanh thu nhập theo kỳ</h2><p className="muted">Nhập số GST được hưởng đã xác định với đối tác, không tự tính tỷ lệ chia sẻ.</p></div>{canCreate&&<button className="action-primary" disabled={busy} onClick={()=>setOpened(!opened)}>{opened?'Đóng nhập liệu':'+ Nhập doanh thu'}</button>}</div>
 {message&&<p className="notice" role="alert">{message}</p>}
 {opened&&canCreate&&<><label>Đối tác<select disabled={busy} value={partner} onChange={e=>{setPartner(e.target.value);setRows([row()]);setSource(null);}}><option value="">Chọn đối tác</option>{refs.partners.map((p:any)=><option key={p.id} value={p.id}>{p.partnerKey} · {p.legalName}</option>)}</select></label><div className="form-actions"><button disabled={busy} onClick={template}>Tải mẫu bảng tính</button><label>Nhập CSV / XLSX<input type="file" accept=".csv,.xlsx" disabled={busy||!partner} onChange={e=>{const f=e.target.files?.[0];if(f)void importFile(f);e.target.value='';}}/></label></div>
 {rows.map((r,i)=><section className="invoice-preview" key={i}><div className="panel-heading"><h3>Dòng {i+1}</h3>{rows.length>1&&<button disabled={busy} onClick={()=>setRows(rows.filter((_,j)=>i!==j))}>Bỏ dòng</button>}</div><div className="partner-grid">
 <label>Kỳ doanh thu<input type="month" disabled={busy} value={r.period} onChange={e=>change(i,'period',e.target.value)}/></label><label>Dịch vụ cha<select disabled={busy} value={r.serviceId} onChange={e=>change(i,'serviceId',e.target.value)}><option value="">Chọn dịch vụ</option>{refs.services.map((s:any)=><option key={s.id} value={s.id}>{s.serviceCode} · {s.serviceName}</option>)}</select></label>
 <label>Hợp đồng đầu ra<select disabled={busy} value={r.contractId} onChange={e=>{const c=refs.contracts.find((v:any)=>v.id===e.target.value);setRows(v=>v.map((x,j)=>j===i?{...x,contractId:e.target.value,currency:c?.currency??x.currency}:x));}}><option value="">Chọn hợp đồng</option>{refs.contracts.filter((c:any)=>c.partnerId===partner&&c.services.some((s:any)=>s.serviceId===r.serviceId)).map((c:any)=><option key={c.id} value={c.id}>{c.contractCode} · {c.contractNumber} · {c.currency}</option>)}</select></label>
 <label>Tiền tệ gốc<select disabled={busy} value={r.currency} onChange={e=>change(i,'currency',e.target.value)}><option>VND</option><option>USD</option></select></label><label>Doanh thu GST được hưởng ({r.currency})<input type="number" min="0" step={r.currency==='VND'?'1':'.01'} disabled={busy} value={r.amount} onChange={e=>change(i,'amount',e.target.value)}/></label><label>Khấu trừ đã xác nhận ({r.currency})<input type="number" min="0" step={r.currency==='VND'?'1':'.01'} disabled={busy} value={r.deduction} onChange={e=>change(i,'deduction',e.target.value)}/></label><label>Tỷ giá báo cáo (VND / USD)<input type="number" min="0.00000001" step="any" disabled={busy} value={r.fxRate} onChange={e=>change(i,'fxRate',e.target.value)}/></label><label>Ghi chú<textarea disabled={busy} value={r.note} onChange={e=>change(i,'note',e.target.value)}/></label></div>
 <p>Quy đổi doanh thu: <b>{Number(r.fxRate)>0?num(r.currency==='USD'?r.amount:Number(r.amount)/Number(r.fxRate)):'—'} USD</b> · <b>{Number(r.fxRate)>0?num(r.currency==='VND'?r.amount:Number(r.amount)*Number(r.fxRate),'VND'):'—'} VND</b></p></section>)}
 <button disabled={busy||rows.length>=100} onClick={()=>setRows([...rows,row()])}>+ Thêm dòng</button><label>Chứng từ nguồn tùy chọn (PDF / PNG / JPEG / bảng theo mẫu, tối đa 5 MB)<input type="file" accept=".pdf,.png,.jpg,.jpeg,.csv,.xlsx" disabled={busy} onChange={e=>setSource(e.target.files?.[0]??null)}/>{source&&<small>{source.name} <button disabled={busy} onClick={()=>setSource(null)}>Bỏ chứng từ</button></small>}</label><p className="muted">Lưu bản nháp chưa ghi nhận doanh thu. Chỉ số liệu đã duyệt mới được đưa vào tổng và tạo Invoice.</p><button className="action-primary" disabled={busy||!partner||rows.some(r=>!r.serviceId||!r.contractId||!r.amount||!r.fxRate)} onClick={()=>void save()}>Lưu bản nháp</button></>}
 <div className="table-scroll"><table><thead><tr><th>Mã / đối tác</th><th>Dịch vụ / kỳ</th><th>Số GST được hưởng</th><th>USD quy đổi</th><th>VND quy đổi</th><th>Trạng thái / thao tác</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td>{i.reconCode}<small>{i.partner} · {i.contract}</small>{i.source&&<a href={'/api/v1/manual-revenue/'+i.id+'/source'}>Chứng từ nguồn</a>}</td><td>{refs.services.find((s:any)=>s.id===i.payload.serviceId)?.serviceName??i.payload.serviceId}<small>{i.payload.period}</small></td><td className="number">{num(i.payload.amount,i.payload.currency)} {i.payload.currency}<small>Khấu trừ: {num(i.payload.deduction,i.payload.currency)}</small></td><td className="number">{num(i.payload.usd)}</td><td className="number">{num(i.payload.vnd,'VND')}</td><td>{i.status==='DRAFT'?'Nháp':i.status==='PENDING_APPROVAL'?'Chờ duyệt':'Đã duyệt'}{i.status==='DRAFT'&&permissions.includes('RECON_REVIEW')&&<button disabled={busy} onClick={()=>void act(i,'submit')}>Gửi kiểm tra</button>}{i.status==='PENDING_APPROVAL'&&permissions.includes('RECON_APPROVE')&&<button disabled={busy} className="action-primary" onClick={()=>void act(i,'approve')}>Duyệt doanh thu</button>}{i.status!=='APPROVED'&&permissions.includes('RECON_CANCEL')&&<button disabled={busy} onClick={()=>void act(i,'cancel')}>Hủy bản nháp</button>}</td></tr>)}</tbody></table></div>{!items.length&&<p className="muted">Chưa có bản nhập theo kỳ.</p>}<div className="pagination"><span>{total} bản ghi · Trang {page}</span><button disabled={busy||page===1} onClick={()=>setPage(page-1)}>Trang trước</button><button disabled={busy||page*50>=total} onClick={()=>setPage(page+1)}>Trang sau</button></div>
 <details><summary>Tỷ giá báo cáo theo kỳ cho doanh thu USD hiện có</summary><p className="muted">Bản nhập mới giữ tỷ giá riêng đã duyệt. Tỷ giá dưới đây bổ sung quy đổi cho doanh thu cũ chưa có tỷ giá báo cáo.</p>{permissions.includes('SYSTEM_CONFIG_EDIT')&&<div className="partner-grid"><label>Kỳ<input type="month" value={fx.period} onChange={e=>setFx({...fx,period:e.target.value})}/></label><label>VND / USD<input type="number" value={fx.rate} onChange={e=>setFx({...fx,rate:e.target.value})}/></label><label>Nguồn tỷ giá<input value={fx.source} onChange={e=>setFx({...fx,source:e.target.value})}/></label><button disabled={busy||!fx.rate||!fx.source.trim()} onClick={()=>void saveFx()}>Lưu tỷ giá theo kỳ</button></div>}<ul>{rates.map(r=><li key={r.period}>{r.period}: {r.rate} VND/USD · {r.source}</li>)}</ul></details>
 </section>;
}
