import React,{useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
type Props={permissions:string[];csrf:string;request:(path:string,body?:unknown,csrf?:string)=>Promise<any>};
function Intake({refs,onClose,onSaved,...props}:Props&{refs:any;onClose:()=>void;onSaved:()=>Promise<void>}){
 const dialog=useRef<HTMLDialogElement>(null),revision=useRef(0);
 const [selection,setSelection]=useState({partnerId:'',serviceId:'',period:''}),[file,setFile]=useState<File|null>(null),[check,setCheck]=useState<any>(null),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{dialog.current?.showModal();return()=>dialog.current?.close();},[]);
 function change(key:string,value:string){revision.current++;setSelection(s=>({...s,[key]:value}));setCheck(null);setConfirmed(false);setMessage('');}
 async function preflight(){const current=revision.current;setBusy(true);setMessage('');setCheck(null);setConfirmed(false);try{const result=await props.request('/output-recon/preflight?'+new URLSearchParams(selection));if(current===revision.current)setCheck(result);}catch(e){setMessage(e instanceof Error?e.message:'Không thể kiểm tra.');}finally{setBusy(false);}}
 async function submit(e:React.FormEvent){e.preventDefault();if(busy||saved||!check||!file)return;
 if(file.size>5*1024*1024||file.size===0||!file.name.toLowerCase().endsWith('.pdf')){setMessage('Chọn tệp PDF tối đa 5 MB.');return;}
 setBusy(true);setMessage('');try{const base64=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('Không đọc được PDF.'));reader.readAsDataURL(file);});
 await props.request('/output-recon/uploads',{...selection,filename:file.name,base64,fingerprint:check.fingerprint,confirmNewVersion:confirmed},props.csrf);setSaved(true);try{await onSaved();onClose();}catch{setMessage('PDF đã được nhận. Đóng cửa sổ và tải lại danh sách.');}
 }catch(e){setMessage(e instanceof Error?e.message:'Không thể nhận PDF.');setCheck(null);setConfirmed(false);}finally{setBusy(false);}}
 return createPortal(<dialog ref={dialog} className="partner-dialog" aria-labelledby="intake-title" onCancel={e=>{if(busy)e.preventDefault();else onClose();}}><div className="partner-dialog-heading"><div><h2 id="intake-title">Nhận PDF đối soát đầu ra</h2><p className="muted">Lưu bản gốc để kiểm tra trước khi chốt đối soát và doanh thu.</p></div><button disabled={busy} onClick={onClose}>Đóng</button></div><form onSubmit={submit}><div className="partner-dialog-body"><fieldset disabled={busy||saved}><div className="partner-grid">
 <label>Đối tác *<select required value={selection.partnerId} onChange={e=>change('partnerId',e.target.value)}><option value="">Chọn đối tác…</option>{refs.partners.map((p:any)=><option key={p.id} value={p.id}>{p.partnerKey} · {p.legalName}</option>)}</select></label>
 <label>Dịch vụ *<select required value={selection.serviceId} onChange={e=>change('serviceId',e.target.value)}><option value="">Chọn dịch vụ…</option>{refs.services.map((s:any)=><option key={s.id} value={s.id}>{s.serviceKey} · {s.serviceName}</option>)}</select></label>
 <label>Kỳ đối soát *<input required type="month" min="2000-01" max="2100-12" value={selection.period} onChange={e=>change('period',e.target.value)}/></label><label>PDF gốc *<input required type="file" accept=".pdf,application/pdf" onChange={e=>{setFile(e.target.files?.[0]??null);setMessage('');}}/><span className="hint">Tối đa 5 MB.</span></label></div>
 <button type="button" disabled={!selection.partnerId||!selection.serviceId||!selection.period} onClick={()=>void preflight()}>Kiểm tra trùng và liên kết</button>
 {check&&<section aria-label="Kết quả kiểm tra"><p className="notice" role="status">{check.message}</p><p><b>Khóa đối soát:</b> {check.businessKey}</p><p>{check.uploads.length} PDF đã nhận · {check.reconciliations.length} đối soát hiện hành</p><p><b>Hợp đồng đầu ra phù hợp:</b> {check.contracts.map((c:any)=>c.contractCode+' · '+c.contractName).join('; ')||'Chưa có hợp đồng Active phù hợp'}</p><p className="hint">Đối tác, dịch vụ và kỳ đang do bạn chọn. Nội dung PDF chưa được đọc và xác minh; chưa tạo doanh thu hoặc thay thế bản cũ.</p>{check.action==='CONFIRM_REPLACE'&&<label className="recon-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Tôi xác nhận nhận bản PDF mới để kiểm tra và giữ nguyên dữ liệu cũ.</label>}</section>}
 </fieldset>{message&&<p className="notice" role="alert">{message}</p>}</div><div className="partner-dialog-footer"><button type="button" disabled={busy} onClick={onClose}>Đóng</button>{!saved&&<button className="action-primary" disabled={busy||!file||!check||check.action==='BLOCK_FINANCIAL_DEPENDENCY'||(check.action==='CONFIRM_REPLACE'&&!confirmed)}>{busy?'Đang xử lý…':'Nhận PDF để kiểm tra'}</button>}</div></form></dialog>,document.body);
}
export function OutputRecon(props:Props){
 const [data,setData]=useState<any>(null),[refs,setRefs]=useState<any>(null),[editor,setEditor]=useState(false),[page,setPage]=useState(1),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[period,setPeriod]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const path=`/output-recon/uploads?page=${page}&search=${encodeURIComponent(query)}${period?'&period='+period:''}`;
 async function load(){setData(await props.request(path));}
 useEffect(()=>{let cancelled=false;setBusy(true);setMessage('');void props.request(path).then(d=>{if(!cancelled)setData(d);}).catch(e=>{if(!cancelled)setMessage(e.message);}).finally(()=>{if(!cancelled)setBusy(false);});return()=>{cancelled=true;};},[path]);
 async function open(){setBusy(true);setMessage('');try{setRefs(await props.request('/output-recon/references'));setEditor(true);}catch(e){setMessage(e instanceof Error?e.message:'Không thể mở biểu mẫu.');}finally{setBusy(false);}}
 return <section className="panel"><h2>PDF đối soát đầu ra</h2><p className="muted">Nhận và lưu PDF gốc. Bước đọc PDF, kiểm tra số liệu và chốt doanh thu đang được bổ sung.</p><form className="list-toolbar" onSubmit={e=>{e.preventDefault();setPage(1);setQuery(search);if(search===query)void load().catch(e=>setMessage(e.message));}}><input aria-label="Tìm PDF đối soát" placeholder="Tìm mã, đối tác hoặc dịch vụ…" value={search} onChange={e=>setSearch(e.target.value)}/><button disabled={busy}>Tìm kiếm</button>{props.permissions.includes('RECON_UPLOAD')&&<button type="button" className="action-primary" disabled={busy} onClick={()=>void open()}>+ Nhận PDF</button>}<button type="button" disabled={busy} onClick={()=>void load().catch(e=>setMessage(e.message))}>Refresh</button><input aria-label="Lọc kỳ đối soát" type="month" min="2000-01" max="2100-12" value={period} onChange={e=>{setPeriod(e.target.value);setPage(1);}}/></form>{message&&<p className="notice" role="alert">{message}</p>}{busy&&<p role="status">Đang tải…</p>}<div className="table-scroll"><table className="recon-table"><thead><tr>{['Mã PDF','Đối tác','Dịch vụ','Kỳ','Tệp gốc','Trạng thái','Người nhận','Thao tác'].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{data?.items.map((r:any)=><tr key={r.id}><td>{r.uploadCode}</td><td>{r.partner.legalName}</td><td>{r.service.serviceKey}</td><td>{r.period}</td><td>{r.attachment.originalFilename}</td><td><span className="status-badge inactive">{r.status==='UPLOADED'?'Đã nhận · Chờ kiểm tra':r.status}</span></td><td>{r.createdBy.fullName}</td><td><a href={'/api/v1/output-recon/uploads/'+r.id+'/download'}>Tải PDF gốc</a></td></tr>)}{data?.total===0&&<tr><td colSpan={8}>Chưa nhận PDF đối soát.</td></tr>}</tbody></table></div><div className="pagination"><span>{data?.total??0} PDF · Trang {page}/{Math.max(1,Math.ceil((data?.total??0)/50))}</span><button disabled={busy||page===1} onClick={()=>setPage(page-1)}>Trang trước</button><button disabled={busy||page*50>=(data?.total??0)} onClick={()=>setPage(page+1)}>Trang sau</button></div>{editor&&refs&&<Intake {...props} refs={refs} onClose={()=>setEditor(false)} onSaved={load}/>}</section>;
}
