import React,{useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {ReconReading} from './ReconReading';
type Props={permissions:string[];csrf:string;request:(path:string,body?:unknown,csrf?:string)=>Promise<any>};
function Intake({refs,onClose,onUploaded,...props}:Props&{refs:any;onClose:()=>void;onUploaded:(id:string)=>Promise<void>}){
 const dialog=useRef<HTMLDialogElement>(null);
 const [partnerId,setPartnerId]=useState<string>(refs.partners.find((p:any)=>p.partnerKey==='MOVITEL'||/^movitel\b/i.test(p.legalName))?.id??'');
 const [file,setFile]=useState<File|null>(null),[inspected,setInspected]=useState<any>(null),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[savedId,setSavedId]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{dialog.current?.showModal();return()=>dialog.current?.close();},[]);
 function reset(){setInspected(null);setConfirmed(false);setMessage('');}
 async function submit(e:React.FormEvent){e.preventDefault();if(busy||!file)return;setBusy(true);setMessage('');
  try{
   if(savedId){await onUploaded(savedId);return;}
   if(file.size>5*1024*1024||file.size===0||!file.name.toLowerCase().endsWith('.pdf'))throw new Error('Chọn tệp PDF tối đa 5 MB.');
   const base64=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('Không đọc được PDF.'));reader.readAsDataURL(file);});
   const result=inspected??await props.request('/output-recon/inspect',{partnerId,filename:file.name,base64},props.csrf);setInspected(result);
   if(!result.selection){setMessage(result.message);return;}
   const check=result.preflight;
   if(check.action==='BLOCK_FINANCIAL_DEPENDENCY'){setMessage(check.message);return;}
   if(check.action==='CONFIRM_REPLACE'&&!confirmed)return;
   const received=await props.request('/output-recon/uploads',{...result.selection,filename:file.name,base64,fingerprint:check.fingerprint,confirmNewVersion:confirmed},props.csrf);setSavedId(received.item.id);
   try{await props.request('/output-recon/uploads/'+received.item.id+'/read',{expectedUpdatedAt:received.item.updatedAt,forceOcr:false},props.csrf);}catch{setMessage('PDF đã upload. Mở màn hình kiểm tra để đọc lại nếu cần.');}
   await onUploaded(received.item.id);
  }catch(e){setMessage(e instanceof Error?e.message:'Không thể upload PDF.');if(!savedId){setInspected(null);setConfirmed(false);}}
  finally{setBusy(false);}
 }
 return createPortal(<dialog ref={dialog} className="partner-dialog" aria-labelledby="intake-title" onCancel={e=>{if(busy)e.preventDefault();else onClose();}}><div className="partner-dialog-heading"><div><h2 id="intake-title">1. Upload file PDF</h2><p className="muted">Chọn bản đối soát gốc. Hệ thống đọc dịch vụ và kỳ từ PDF, kiểm tra trùng, rồi mở màn hình kiểm tra.</p></div><button disabled={busy} onClick={onClose}>Đóng</button></div><form onSubmit={submit}><div className="partner-dialog-body"><fieldset disabled={busy||!!savedId}><div className="partner-grid">
 <label>Đối tác *<select required value={partnerId} onChange={e=>{setPartnerId(e.target.value);reset();}}><option value="">Chọn đối tác…</option>{refs.partners.map((p:any)=><option key={p.id} value={p.id}>{p.partnerKey} · {p.legalName}</option>)}</select></label>
 <label>PDF gốc *<input required type="file" accept=".pdf,application/pdf" onChange={e=>{setFile(e.target.files?.[0]??null);reset();}}/><span className="hint">Mỗi lần upload 1 PDF, tối đa 5 MB.</span></label></div>
 {inspected&&<section aria-label="Kết quả nhận diện PDF"><p><b>Dịch vụ từ PDF:</b> {inspected.parsed.service||'Chưa nhận diện'}</p><p><b>Kỳ từ PDF:</b> {inspected.parsed.period||'Chưa nhận diện'}</p><p className="notice" role="status">{inspected.message}</p>{inspected.preflight?.action==='CONFIRM_REPLACE'&&<label className="recon-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Đã có PDF/đối soát cùng kỳ. Tôi xác nhận upload bản mới để kiểm tra, giữ lịch sử cũ.</label>}</section>}
 </fieldset>{busy&&<p role="status">Đang đọc PDF và kiểm tra trùng. Bản scan có thể cần khoảng một phút…</p>}{message&&<p className="notice" role="alert">{message}</p>}</div><div className="partner-dialog-footer"><button type="button" disabled={busy} onClick={onClose}>Đóng</button><button className="action-primary" disabled={busy||!file||!partnerId||inspected?.preflight?.action==='BLOCK_FINANCIAL_DEPENDENCY'||(inspected?.preflight?.action==='CONFIRM_REPLACE'&&!confirmed)}>{busy?'Đang xử lý…':savedId?'Mở kiểm tra PDF':'Upload PDF'}</button></div></form></dialog>,document.body);
}
export function OutputRecon(props:Props){
 const [data,setData]=useState<any>(null),[refs,setRefs]=useState<any>(null),[editor,setEditor]=useState(false),[reading,setReading]=useState<any>(null),[page,setPage]=useState(1),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[period,setPeriod]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const path=`/output-recon/uploads?page=${page}&search=${encodeURIComponent(query)}${period?'&period='+period:''}`;
 async function load(){setData(await props.request(path));}
 useEffect(()=>{let cancelled=false;setBusy(true);setMessage('');void props.request(path).then(d=>{if(!cancelled)setData(d);}).catch(e=>{if(!cancelled)setMessage(e.message);}).finally(()=>{if(!cancelled)setBusy(false);});return()=>{cancelled=true;};},[path]);
 async function review(id:string){setBusy(true);setMessage('');try{setReading(await props.request('/output-recon/uploads/'+id));}catch(e){setMessage(e instanceof Error?e.message:'Không thể mở PDF.');}finally{setBusy(false);}}
 async function open(){setBusy(true);setMessage('');try{setRefs(await props.request('/output-recon/references'));setEditor(true);}catch(e){setMessage(e instanceof Error?e.message:'Không thể mở biểu mẫu.');}finally{setBusy(false);}}
 return <section className="panel"><h2>Đối soát đầu ra</h2><p className="muted">Nhận PDF, đọc chữ hoặc OCR ảnh scan và đối chiếu dịch vụ, kỳ, hợp đồng trước khi kiểm tra số liệu.</p><form className="list-toolbar" onSubmit={e=>{e.preventDefault();setPage(1);setQuery(search);if(search===query)void load().catch(e=>setMessage(e.message));}}><input aria-label="Tìm PDF đối soát" placeholder="Tìm mã, đối tác hoặc dịch vụ…" value={search} onChange={e=>setSearch(e.target.value)}/><button disabled={busy}>Tìm kiếm</button>{props.permissions.includes('RECON_UPLOAD')&&<button type="button" className="action-primary" disabled={busy} onClick={()=>void open()}>1. Upload file PDF</button>}<button type="button" disabled={busy} onClick={()=>void load().catch(e=>setMessage(e.message))}>Refresh</button><input aria-label="Lọc kỳ đối soát" type="month" min="2000-01" max="2100-12" value={period} onChange={e=>{setPeriod(e.target.value);setPage(1);}}/></form>{message&&<p className="notice" role="alert">{message}</p>}{busy&&<p role="status">Đang tải…</p>}<div className="table-scroll"><table className="recon-table"><thead><tr>{['Mã PDF','Đối tác','Dịch vụ','Kỳ','Tệp gốc','Trạng thái','Người nhận','Thao tác'].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{data?.items.map((r:any)=><tr key={r.id}><td>{r.uploadCode}</td><td>{r.partner.legalName}</td><td>{r.service.serviceKey}</td><td>{r.period}</td><td>{r.attachment.originalFilename}</td><td><span className="status-badge inactive">{r.status==='UPLOADED'?'Đã nhận · Chờ đọc':r.status==='OCR_EXTRACTED'?'Đã đọc · Chờ kiểm tra':r.status==='UNDER_REVIEW'?'Cần kiểm tra dịch vụ/kỳ':r.status}</span></td><td>{r.createdBy.fullName}</td><td><button disabled={busy} onClick={()=>void review(r.id)}>Kiểm tra PDF</button> <a href={'/api/v1/output-recon/uploads/'+r.id+'/download'}>Tải PDF gốc</a></td></tr>)}{data?.total===0&&<tr><td colSpan={8}>Chưa nhận PDF đối soát.</td></tr>}</tbody></table></div><div className="pagination"><span>{data?.total??0} PDF · Trang {page}/{Math.max(1,Math.ceil((data?.total??0)/50))}</span><button disabled={busy||page===1} onClick={()=>setPage(page-1)}>Trang trước</button><button disabled={busy||page*50>=(data?.total??0)} onClick={()=>setPage(page+1)}>Trang sau</button></div>{reading&&<ReconReading {...props} initial={reading} onClose={()=>setReading(null)} onSaved={load}/ >}{editor&&refs&&<Intake {...props} refs={refs} onClose={()=>setEditor(false)} onUploaded={async(id)=>{const detail=await props.request('/output-recon/uploads/'+id);setEditor(false);setReading(detail);await load();}}/>}</section>;
}
