import React,{useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
type Props={permissions:string[];csrf:string;request:(path:string,body?:unknown,csrf?:string)=>Promise<any>;initial:any;onClose:()=>void;onSaved:()=>Promise<void>};
export function ReconReading(props:Props){
 const dialog=useRef<HTMLDialogElement>(null),[data,setData]=useState(props.initial),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[page,setPage]=useState(1),[previewError,setPreviewError]=useState(false),[previewKey,setPreviewKey]=useState(0);
 useEffect(()=>{dialog.current?.showModal();return()=>dialog.current?.close();},[]);
 async function read(forceOcr=false){setBusy(true);setMessage('');try{const result=await props.request('/output-recon/uploads/'+data.item.id+'/read',{expectedUpdatedAt:data.item.updatedAt,forceOcr},props.csrf);setData(result);try{await props.onSaved();}catch{setMessage('Đã lưu kết quả đọc. Đóng cửa sổ và tải lại danh sách.');}}catch(e){setMessage(e instanceof Error?e.message:'Không thể đọc PDF.');}finally{setBusy(false);}}
 const p=data.parsed,a=data.assessment;
 return createPortal(<dialog ref={dialog} className="partner-dialog" aria-labelledby="reading-title" onCancel={e=>{if(busy)e.preventDefault();else props.onClose();}}><div className="partner-dialog-heading"><div><h2 id="reading-title">Kiểm tra nội dung PDF · {data.item.uploadCode}</h2><p className="muted">{data.item.attachment.originalFilename}</p></div><button disabled={busy} onClick={props.onClose}>Đóng</button></div><div className="partner-dialog-body"><p><b>Đã chọn:</b> {data.item.partner.legalName} · {data.item.service.serviceKey} · {data.item.period}</p><a href={'/api/v1/output-recon/uploads/'+data.item.id+'/download'}>Tải PDF gốc để đối chiếu</a>{busy&&<p role="status">Đang đọc PDF. File scan có thể cần khoảng một phút…</p>}{message&&<p className="notice" role="alert">{message}</p>}
 {a&&<><p className={'notice '+(a.identity.state==='MATCHED'?'recon-match':'')} role="status">{a.identity.message}</p>{a.financialBlocked&&<p className="notice" role="alert">{a.financialMessage}</p>}</>}
 {p&&<><div className="partner-grid"><label>Dịch vụ đọc từ PDF<input readOnly value={p.service||'Chưa xác định'}/></label><label>Kỳ đọc từ PDF<input readOnly value={p.period||'Chưa xác định'}/></label><label>Số hợp đồng trên PDF<input readOnly value={p.agreementNo||'Chưa xác định'}/></label><label>Ngày ký trên PDF<input readOnly value={p.agreementSignedDate||'Chưa xác định'}/></label><label>Exchange rate trên PDF<input readOnly value={p.exchangeRate??'Chưa xác định'}/></label><label>Total revenue USD trên PDF<input readOnly value={p.totalRevenueUsd??'Chưa xác định'}/></label></div><p><b>Hợp đồng phù hợp:</b> {a?.contracts.map((c:any)=>c.contractCode+' · '+c.contractName).join('; ')||'Chưa tìm thấy hợp đồng đầu ra Active trùng số, dịch vụ và kỳ'}</p>{a?.contractState==='AMBIGUOUS'&&<p className="notice">Có nhiều hợp đồng phù hợp. Chưa tự chọn hợp đồng.</p>}{p.inferredFromAgreement&&<p className="notice">Dịch vụ được suy ra từ số hợp đồng. Cần đối chiếu tiêu đề PDF.</p>}<p className="hint">Những giá trị này được đọc từ PDF và chưa được xác nhận. Bảng chi tiết MZN/USD, thuế và chia sẻ doanh thu sẽ được kiểm tra ở bước tiếp theo; chưa chốt hoặc tạo doanh thu.</p><p className="muted">{data.extractionData.pages.map((v:any)=>`Trang ${v.page}: ${v.method==='OCR'?'OCR ảnh scan':'Chữ trong PDF'}`).join(' · ')}</p><details><summary>Nội dung chữ đã đọc</summary><pre className="recon-raw">{data.rawText}</pre></details></>}
  {!busy&&<section className="recon-original-preview" aria-label="Preview file scan"><h3>Preview file scan gốc</h3><div className="list-toolbar"><label>Trang PDF<select value={page} onChange={e=>{setPage(Number(e.target.value));setPreviewError(false);}}>{Array.from({length:data.extractionData?.pages?.length??1},(_,i)=><option key={i+1} value={i+1}>{i+1}</option>)}</select></label><a href={'/api/v1/output-recon/uploads/'+data.item.id+'/download'}>Tải PDF gốc</a></div>{previewError?<p className="notice" role="alert">Không tải được trang scan. <button onClick={()=>{setPreviewError(false);setPreviewKey(v=>v+1);}}>Tải lại preview</button></p>:<img key={page+'-'+previewKey} src={'/api/v1/output-recon/uploads/'+data.item.id+'/preview?page='+page} alt={'Trang '+page+' của PDF đối soát gốc'} onError={()=>setPreviewError(true)}/>}<p className="hint">Bản gốc giữ nguyên. Ảnh xem trước giữ đúng tỷ lệ và hướng trang PDF.</p></section>}
 {!p&&<p>Chưa đọc nội dung. Bấm “Đọc PDF” để kiểm tra dịch vụ, kỳ và số hợp đồng.</p>}</div><div className="partner-dialog-footer"><button disabled={busy} onClick={props.onClose}>Đóng</button>{props.permissions.includes('RECON_UPLOAD')&&['UPLOADED','OCR_EXTRACTED','UNDER_REVIEW'].includes(data.item.status)&&<><button disabled={busy} onClick={()=>void read(true)}>Đọc bằng OCR ảnh scan</button><button className="action-primary" disabled={busy} onClick={()=>void read()}>{data.rawText?'Đọc lại PDF':'Đọc PDF'}</button></>}</div></dialog>,document.body);
}
