import React,{useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
type Props={permissions:string[];csrf:string;request:(path:string,body?:unknown,csrf?:string)=>Promise<any>};
const statuses:Record<string,string>={DRAFT:'Draft',ACTIVE:'Active',EXPIRED:'Expired',TERMINATED:'Terminated',SUSPENDED:'Suspended'};
function Editor({item,refs,onClose,onSaved,...props}:Props&{item:any;refs:any;onClose:()=>void;onSaved:()=>Promise<void>}){
 const dialog=useRef<HTMLDialogElement>(null);const[busy,setBusy]=useState(false),[saved,setSaved]=useState(false),[message,setMessage]=useState(''),[deleting,setDeleting]=useState(false);
 const editable=props.permissions.includes(item?'CONTRACT_EDIT':'CONTRACT_CREATE');
 const selected=item?.services.filter((s:any)=>s.dgcStatus!=='INACTIVE').map((s:any)=>s.serviceId)??[];
 useEffect(()=>{dialog.current?.showModal();return()=>dialog.current?.close();},[]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy||saved)return;const f=new FormData(e.currentTarget);const s=(k:string)=>String(f.get(k)??'').trim();
 const body:any=deleting?{expectedUpdatedAt:item.updatedAt,reason:s('deleteReason')}:{contractName:s('contractName'),contractNumber:s('contractNumber')||null,partnerId:s('partnerId'),dgcDirection:s('dgcDirection'),serviceIds:f.getAll('serviceIds'),currency:s('currency'),status:s('status'),paymentTermDays:Number(s('paymentTermDays')),billingCycle:s('billingCycle'),ownerEmail:s('ownerEmail')||null,attachmentUrl:s('attachmentUrl')||null,notes:s('notes')||null};
 if(!deleting){for(const k of ['revenueShareRate','fixedFee','taxRate'])body[k]=s(k)||'0';for(const k of ['signingDate','effectiveDate','expiryDate'])body[k]=s(k)||null;if(item){body.expectedUpdatedAt=item.updatedAt;body.reason=s('reason');}}
 setBusy(true);setMessage('');try{await props.request(item?`/service-contracts/${item.id}/${deleting?'delete':'update'}`:'/service-contracts',body,props.csrf);setSaved(true);try{await onSaved();onClose();}catch{setMessage('Đã lưu. Đóng cửa sổ và tải lại danh sách.');}}catch(e){setMessage(e instanceof Error?e.message:'Không thể lưu hợp đồng.');}finally{setBusy(false);}}
 const input=(name:string,label:string,type='text',value:any='')=><label>{label}<input name={name} type={type} defaultValue={item?.[name]??value} maxLength={500}/></label>;
 return createPortal(<dialog ref={dialog} className="partner-dialog" aria-labelledby="contract-title" onCancel={e=>{if(busy)e.preventDefault();else onClose();}}><div className="partner-dialog-heading"><div><h2 id="contract-title">{deleting?'Xác nhận xóa hợp đồng':item?'Hồ sơ hợp đồng':'Thêm mới hợp đồng'}</h2><p className="muted">Hợp đồng dịch vụ đầu vào, đầu ra hoặc khác.</p></div><button onClick={onClose} disabled={busy}>Đóng</button></div><form onSubmit={submit}><div className="partner-dialog-body">
 {deleting?<fieldset disabled={busy||saved}><p>Xóa vĩnh viễn {item.contractCode}? Chỉ hợp đồng chưa có liên kết mới được xóa.</p><label>Lý do xóa *<input name="deleteReason" required maxLength={500}/></label></fieldset>:<fieldset disabled={busy||saved||!editable}><div className="partner-grid">
 {item&&<label>Contract_ID<input value={item.contractCode} readOnly/></label>}{input('contractNumber','Số hợp đồng')}
 <label>Loại hợp đồng<select name="dgcDirection" defaultValue={item?.dgcDirection??'Output'}>{['Input','Output','Other'].map(s=><option key={s}>{s}</option>)}</select></label>
 <label>Trạng thái<select name="status" defaultValue={item?.status??'DRAFT'}>{Object.entries(statuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
 <label className="partner-wide">Tên hợp đồng *<input name="contractName" required maxLength={500} defaultValue={item?.contractName??''}/></label>
 <label className="partner-wide">Đối tác *<select name="partnerId" required defaultValue={item?.partnerId??''}><option value="">Chọn đối tác…</option>{refs.partners.map((p:any)=><option key={p.id} value={p.id}>{p.partnerKey} · {p.legalName} · {p.status}</option>)}</select></label>
 <div className="partner-wide"><b>Dịch vụ</b><div className="contract-service-options">{refs.services.map((s:any)=><label key={s.id}><input type="checkbox" name="serviceIds" value={s.id} defaultChecked={selected.includes(s.id)}/>{s.serviceKey} · {s.serviceName} · {s.status}</label>)}</div><p className="hint">Bỏ chọn sẽ giữ liên kết cũ ở trạng thái Inactive.</p></div>
 {(['signingDate','effectiveDate','expiryDate'] as const).map((k,i)=><label key={k}>{['Ngày ký','Ngày bắt đầu','Ngày kết thúc'][i]}<input name={k} type="date" defaultValue={item?.[k]?.slice(0,10)??''}/></label>)}
 <label>Tiền tệ<select name="currency" defaultValue={item?.currency??'MZN'}>{['MZN','USD','VND'].map(v=><option key={v}>{v}</option>)}</select></label>
 {['revenueShareRate','taxRate'].map((k,i)=><label key={k}>{['Revenue share rate','Tax rate'][i]}<input name={k} type="number" min="0" max="1" step="0.000001" defaultValue={item?.[k]??'0'}/><span className="hint">Nhập tỷ lệ: 0.15 = 15%</span></label>)}
 <label>Fixed fee<input name="fixedFee" type="number" min="0" step="0.0001" defaultValue={item?.fixedFee??'0'}/></label>
 <label>Payment term days<input name="paymentTermDays" type="number" min="0" max="3650" step="1" defaultValue={item?.paymentTermDays??30}/></label>
 {input('billingCycle','Chu kỳ thanh toán','text','Monthly')}{input('ownerEmail','Người phụ trách (email)','email')}{input('attachmentUrl','Liên kết tài liệu','url')}
 <label className="partner-wide">Ghi chú<textarea name="notes" rows={3} maxLength={4000} defaultValue={item?.notes??''}/></label>{item&&editable&&<label className="partner-wide">Lý do cập nhật *<input name="reason" required maxLength={500}/></label>}
 </div></fieldset>}{item&&!deleting&&<p className="muted">Tạo: {item.createdBy} · {new Date(item.createdAt).toLocaleString('vi-VN')}<br/>Cập nhật: {item.updatedBy} · {new Date(item.updatedAt).toLocaleString('vi-VN')}</p>}{message&&<p role="alert" className="notice">{message}</p>}</div><div className="partner-dialog-footer">{item&&!deleting&&!saved&&editable&&props.permissions.includes('CONTRACT_TERMINATE')&&<button type="button" disabled={busy} onClick={()=>setDeleting(true)}>Xóa hợp đồng…</button>}<button type="button" disabled={busy} onClick={()=>deleting?setDeleting(false):onClose()}>{deleting?'Quay lại':'Đóng'}</button>{!saved&&(editable||deleting)&&<button className="action-primary" disabled={busy}>{busy?'Đang xử lý…':deleting?'Xác nhận xóa':'Lưu hợp đồng'}</button>}</div></form></dialog>,document.body);
}
export function ServiceContracts(props:Props){
 const[data,setData]=useState<any>(null),[refs,setRefs]=useState<any>(null),[editor,setEditor]=useState<any>(null),[page,setPage]=useState(1),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const path=`/service-contracts?page=${page}&search=${encodeURIComponent(query)}${status?'&status='+status:''}`;
 async function load(){setData(await props.request(path));}
 useEffect(()=>{let cancelled=false;setBusy(true);void props.request(path).then(d=>{if(!cancelled)setData(d);}).catch(e=>{if(!cancelled)setMessage(e.message);}).finally(()=>{if(!cancelled)setBusy(false);});return()=>{cancelled=true;};},[path]);
 async function open(id?:string){setBusy(true);setMessage('');try{const r=await props.request('/service-contracts/references');const item=id?(await props.request('/service-contracts/'+id)).item:false;setRefs(r);setEditor(item);}catch(e){setMessage(e instanceof Error?e.message:'Không thể mở hợp đồng.');}finally{setBusy(false);}}
 return <section className="panel"><h2>Danh sách hợp đồng</h2><form className="list-toolbar" onSubmit={e=>{e.preventDefault();setPage(1);setQuery(search);if(search===query)void load().catch(e=>setMessage(e.message));}}><input aria-label="Tìm hợp đồng" placeholder="Tìm mã, số, tên hợp đồng hoặc đối tác…" value={search} onChange={e=>setSearch(e.target.value)}/><button disabled={busy}>Tìm kiếm</button>{props.permissions.includes('CONTRACT_CREATE')&&<button type="button" className="action-primary" disabled={busy} onClick={()=>void open()}>+ Thêm mới hợp đồng</button>}<button type="button" disabled={busy} onClick={()=>void load().catch(e=>setMessage(e.message))}>Refresh</button><select aria-label="Trạng thái hợp đồng" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">Tất cả trạng thái</option>{Object.entries(statuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></form>{message&&<p role="alert" className="notice">{message}</p>}{busy&&<p role="status">Đang tải…</p>}<div className="table-scroll"><table><thead><tr>{['Contract_ID','Số hợp đồng','Tên hợp đồng','Loại','Đối tác','Dịch vụ','Tiền tệ','Trạng thái','Thao tác'].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{data?.items.map((c:any)=><tr key={c.id}><td>{c.contractCode}</td><td>{c.contractNumber??'—'}</td><td>{c.contractName}</td><td>{c.dgcDirection}</td><td>{c.partner.legalName}</td><td>{c.services.filter((s:any)=>s.dgcStatus!=='INACTIVE').map((s:any)=>s.service.serviceKey).join(', ')||'—'}</td><td>{c.currency}</td><td><span className={'status-badge '+(c.status==='ACTIVE'?'active':'inactive')}>{statuses[c.status]}</span></td><td><button disabled={busy} onClick={()=>void open(c.id)}>Xem hồ sơ</button></td></tr>)}{data?.total===0&&<tr><td colSpan={9}>Chưa có hợp đồng dịch vụ.</td></tr>}</tbody></table></div><div className="pagination"><span>{data?.total??0} hợp đồng · Trang {page}/{Math.max(1,Math.ceil((data?.total??0)/50))}</span><button disabled={busy||page===1} onClick={()=>setPage(page-1)}>Trang trước</button><button disabled={busy||page*50>=(data?.total??0)} onClick={()=>setPage(page+1)}>Trang sau</button></div>{editor!==null&&refs&&<Editor {...props} item={editor||undefined} refs={refs} onClose={()=>setEditor(null)} onSaved={load}/>}</section>;
}
