export const PERMISSIONS = [
  'SYSTEM_VIEW','SYSTEM_CONFIG_EDIT','USER_VIEW','USER_CREATE','USER_EDIT','USER_DISABLE',
  'ROLE_VIEW','ROLE_CREATE','ROLE_EDIT',
  'PARTNER_VIEW','PARTNER_CREATE','PARTNER_EDIT','PARTNER_ARCHIVE',
  'SERVICE_VIEW','SERVICE_CREATE','SERVICE_EDIT','SERVICE_ARCHIVE',
  'CONTRACT_VIEW','CONTRACT_CREATE','CONTRACT_EDIT','CONTRACT_SUBMIT','CONTRACT_APPROVE','CONTRACT_SIGN','CONTRACT_ACTIVATE','CONTRACT_TERMINATE','CONTRACT_ADDENDUM_CREATE',
  'COMMERCIAL_CONFIG_EDIT',
  'PROJECT_VIEW','PROJECT_CREATE','PROJECT_EDIT','PROJECT_ASSIGN','PROJECT_CHANGE_STAGE','PROJECT_QUALIFY','PROJECT_VIEW_ALL',
  'MILESTONE_VIEW','MILESTONE_CREATE','MILESTONE_EDIT','MILESTONE_ACCEPT','MILESTONE_CANCEL','COST_VIEW','COST_CREATE','COST_EDIT','COST_APPROVE','COST_CANCEL','COST_BUDGET_VIEW','COST_BUDGET_REVISE',
  'QUOTATION_VIEW','QUOTATION_CREATE','QUOTATION_EDIT','QUOTATION_REVISE','QUOTATION_SUBMIT','QUOTATION_APPROVE','QUOTATION_SEND','QUOTATION_ACCEPT','QUOTATION_CANCEL',
  'APPROVAL_VIEW','APPROVAL_ACTION',
  'CONTRACT_ACTIVATION_CONDITION_EDIT','CONTRACT_ACTIVATION_CONDITION_WAIVE',
  'BILLING_PLAN_VIEW','BILLING_PLAN_CREATE','BILLING_PLAN_EDIT','BILLING_TRIGGER_MARK','BILLING_TRIGGER_VERIFY',
  'PAYMENT_PLAN_VIEW','PAYMENT_PLAN_EDIT',
  'RECON_VIEW','RECON_UPLOAD','RECON_EDIT_DRAFT','RECON_REVIEW','RECON_VALIDATE','RECON_APPROVE','RECON_SUPERSEDE','RECON_CANCEL','RECON_OVERRIDE',
  'REVENUE_VIEW',
  'INVOICE_SCOPE_VIEW','INVOICE_SCOPE_REBUILD',
  'INVOICE_VIEW','INVOICE_CREATE','INVOICE_APPROVE','INVOICE_ISSUE','INVOICE_CANCEL',
  'AR_VIEW','AP_VIEW',
  'PAYMENT_VIEW','PAYMENT_CREATE','PAYMENT_APPROVE','PAYMENT_POST','PAYMENT_ALLOCATE',
  'REPORT_VIEW','AUDIT_VIEW'
] as const;
export type PermissionCode = typeof PERMISSIONS[number];
